[theme]
primaryColor         = "#3B6E48"
backgroundColor      = "#F8F4F1"
secondaryBackgroundColor = "#F8F4F1"
textColor            = "#1C3A27"
font                 = "sans serif"

[server]
headless = true
