[theme]
primaryColor         = "#3B6E48"
backgroundColor      = "#F0EAE3"
secondaryBackgroundColor = "#EAE3DA"
textColor            = "#1C3A27"
font                 = "sans serif"

[server]
headless = true
